### ISSUE TITLE
EECS 370 Honor Code Violation

### ISSUE THREAD

**Issue by Faryab** [robkeim/random#1]
Hello,

I'm a staff member of the current EECS370 Staff. I see that you have published the 370 solutions online in a public repo. This could have been a mistake so I just wanted to ask you to make this a private repo or take the solutions down. Posting project solutions online is against the engineering honor code and course policy.

This repo [(Specifically here)](https://github.com/robkeim/random/blob/7cf8b515e34076ec31131153515b65d15096e34b/College/eecs370/p3/simulator.c) contains solutions for [EECS370 Projects](https://www.eecs.umich.edu/courses/eecs370/eecs370.f20/projects/).

Thanks,
K. Faryab Haye - EECS 370 Staff
University of Michigan
https://www.eecs.umich.edu/courses/eecs370/eecs370.f20/

**Comment by robkeim** [comment]
Hello K. Faryab Haye,

Apologies for the delay, I'm just seeing the notification now. This was indeed a mistake on my part. I've gone ahead and taken the solutions down.

Thanks,
Rob
